### ISSUE TITLE
Question about exact specs

### ISSUE THREAD

**Issue by dr-sandwich** [tuanictu97/Hackintosh-Dell-Vostro-v3558#1]
Hello, I was just wondering what are the exact specs of this Vostro 3558? Since my model has i3 5005u cpu and I know some other models have different CPUs so I would like to know before I try this out.

**Comment by tuanha1305** [comment]
My hardware info:
i5 5200u
hd 5500
audio: ALC255
nvidia 820M (not supported)

Vào Th 6, 17 thg 4, 2020 vào lúc 01:46 Grizzlywolf <
notifications@github.com> đã viết:

**Comment by tuanha1305** [comment]
My hardware info:
i5 5200u
hd 5500
audio: ALC255
nvidia 820M (not supported)
